
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
info:
  application:
    name: spring-blog
    description: A blog with articles about The Spring Framework.
    author: Dan Vega
    version: '@project.version@'
server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

  jpa:
    hibernate:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
security:
  user:
    name: myusername
    password: mypassword
    email: myemail@example.com

    mail:
      host: smtp.gmail.com
      port: 587
      username: vairussyr97@gmail.com
      password: jopyuautblsbzzta
      properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: true
            starttls:
              enable: true
              auth: true
            connectiontimeout: 5000
            timeout: 3000
            writetimeout: 5000
