management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: A blog with articles about The Spring Framework.
    author: Dan Vega
    version: '@project.version@'

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: password

  sql:
    init:
      mode: always

third:
  spring:
    datasource:
      url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
      username: ${PROD_DB_USERNAME}
      password: ${PROD_DB_PASSWORD}
      name: spring-blog

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes

fourth:
  spring:
    datasource:
      url: jdbc:tc:postgresql:14-alpine:///spring-blog

  sql:
    init:
      mode: always
