management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: spring-blog
    description: A blog with articles about The Spring Framework.
    author: Dan Vega
    version: '@project.version@'

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://containers-us-west-103.railway.app:7525/railway
    username: postgres
    password: UF2sP62678xnpVN0BL3S
    name: spring-blog

  sql:
    init:
      mode: always
